# Generated by Django 3.0.3 on 2020-04-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roza', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('Sehr', models.DateTimeField()),
                ('Iftaar', models.DateTimeField()),
            ],
        ),
    ]
