# Generated by Django 3.0.3 on 2020-04-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rozadate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='roza',
            new_name='roza2',
        ),
    ]
